apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-loadbalancer1
spec:
  replicas: 1
  selector:
    app: nginx-loadbalancer
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-loadbalancer
    spec:
      containers:
      - name: nginx-container
        image: docker.io/sufiaalmas/nginx-image
        ports:
        - containerPort: 80

