apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-loadbalancer3
spec:
  replicas: 1
  selector:
    app: nginx-loadbalancer
  template:
    metadata:
      name: nginx-pod
      labels:
         app: nginx-loadbalancer
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
