apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  tls:
  - secretName: tls-secret
  rules:
  - host: application.com
    http:
      paths:
      - path: 
        backend:
          serviceName: load-service
          servicePort: 80

